version: "3.9"
services:
    trainsim-client:
        build: .
        volumes:
            - ./dist:/usr/share/nginx/html
        ports:
            - 8000:80
        external_links:
            - trainsim-user-service
            - trainsim-itinenary-service